services:
    rabbitmq:
        image: rabbitmq
        container_name: rabbitmq
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./dados:/var/lib/rabbitmq/
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            discovery.type: "single-node"
            ES_JAVA_OPTS: "-Xms2g -Xmx2g"
            xpack.monitoring.enabled: "true"
        volumes:
            - ./esdata:/usr/share/elasticsearch/data

    kibana:
        image: docker.elastic.co/kibana/kibana:7.7.0
        ports:
            - "5601:5601"
        environment:
            ELASTICSEARCH_URL: http://elasticsearch:9200
        depends_on:
            - elasticsearch